In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
dataset = pd.read_csv('Churn_Modelling.csv')

In [3]:
dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [4]:
X = dataset.iloc[:,3:-1].values
y = dataset.iloc[:,-1].values

In [5]:
print(X[0])

[619 'France' 'Female' 42 2 0.0 1 1 1 101348.88]


In [6]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

In [7]:
label_encoder_X1 = LabelEncoder()
X[:,1] = label_encoder_X1.fit_transform(X[:,1])

In [8]:
label_encoder_X2 = LabelEncoder()
X[:,2] = label_encoder_X2.fit_transform(X[:,2])

In [9]:
one_hot_encoder = OneHotEncoder(categorical_features=[1])

In [10]:
X = one_hot_encoder.fit_transform(X).toarray()

In [11]:
#To avoid dummy variable trap
X = X[:,1:]

In [12]:
from sklearn.model_selection import train_test_split

In [13]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [14]:
from sklearn.preprocessing import StandardScaler

In [15]:
scaler = StandardScaler()

In [16]:
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [17]:
print('Shape of training set {}'.format(X_train.shape))

Shape of training set (8000, 11)


In [18]:
from tensorflow.python.keras.models import Sequential
from tensorflow.python.keras.layers import Dense

/Users/tari/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [19]:
classifier = Sequential()

In [20]:
#1st hidden layer
classifier.add(Dense(input_dim= 11, units= 6, kernel_initializer='uniform', activation='relu'))

In [21]:
#2nd hidden layer
classifier.add(Dense(units= 6, kernel_initializer='uniform', activation='relu'))

In [22]:
#Output layer
classifier.add(Dense(units= 1, kernel_initializer='uniform', activation='sigmoid'))

In [23]:
#Compile the model with certain hyperparameters
classifier.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [24]:
classifier.fit(X_train, y_train, batch_size=10, epochs=100)

Epoch 1/100
8000/8000 [==============================]8000/8000 [==============================] - 2s 274us/step - loss: 1.2704 - acc: 0.6518

Epoch 2/100
8000/8000 [==============================]8000/8000 [==============================] - 2s 204us/step - loss: 0.5028 - acc: 0.7957

Epoch 3/100
8000/8000 [==============================]8000/8000 [==============================] - 2s 206us/step - loss: 0.4685 - acc: 0.8014

Epoch 4/100
8000/8000 [==============================]8000/8000 [==============================] - 2s 231us/step - loss: 0.4576 - acc: 0.8040 0s - loss: 0.4523

Epoch 5/100
8000/8000 [==============================]8000/8000 [==============================] - 2s 242us/step - loss: 0.4537 - acc: 0.8042

Epoch 6/100
8000/8000 [==============================]8000/8000 [==============================] - 2s 212us/step - loss: 0.4497 - acc: 0.8055

Epoch 7/100
8000/8000 [==============================]8000/8000 [==============================] - 2s 213us/step - loss: 0.4

8000/8000 [==============================]8000/8000 [==============================] - 2s 201us/step - loss: 0.3335 - acc: 0.8644

Epoch 55/100
8000/8000 [==============================]8000/8000 [==============================] - 2s 203us/step - loss: 0.3337 - acc: 0.8654

Epoch 56/100
8000/8000 [==============================]8000/8000 [==============================] - 2s 203us/step - loss: 0.3334 - acc: 0.8650

Epoch 57/100
8000/8000 [==============================]8000/8000 [==============================] - 2s 203us/step - loss: 0.3332 - acc: 0.8650

Epoch 58/100
8000/8000 [==============================]8000/8000 [==============================] - 2s 205us/step - loss: 0.3331 - acc: 0.8660

Epoch 59/100
8000/8000 [==============================]8000/8000 [==============================] - 2s 223us/step - loss: 0.3329 - acc: 0.8644 0s - loss: 0.3325 - acc: 0

Epoch 60/100
8000/8000 [==============================]8000/8000 [==============================] - 2s 233us/step - loss: 

In [25]:
#Testing the model performance on a testing set
y_pred = classifier.predict(X_test)

In [26]:
y_pred = y_pred > 0.5

In [27]:
from sklearn.metrics import confusion_matrix, f1_score, accuracy_score

In [28]:
confusion_matrix(y_test, y_pred)

array([[1550,   57],
       [ 214,  179]])

In [29]:
print('f1 score ', f1_score(y_test, y_pred))

f1 score  0.5691573926868045


In [30]:
print('Accuracy score ', accuracy_score(y_test, y_pred))

Accuracy score  0.8645


# Single prediction
 - Geography: France
 - Credit Score: 600
 - Gender: Male
 - Age: 40 years old
 - Tenure: 3 years
 - Balance: 60000 USD
 - Number of Products: 2
 - Does this customer have a credit card ? Yes
 - Is this customer an Active Member: Yes
 - Estimated Salary: $50000

In [31]:
single_pred = pd.Series([600, 'France', 'Male', 40, 3, 60000, 2, 1, 1, 50000])

In [32]:
X_single = single_pred.values
X_single = np.reshape(X_single, (1,10))
X_single

array([[600, 'France', 'Male', 40, 3, 60000, 2, 1, 1, 50000]],
      dtype=object)

In [33]:
X_single[:,1] = label_encoder_X1.transform(X_single[:,1])
X_single[:,2] = label_encoder_X2.transform(X_single[:,2])

In [34]:
X_single = one_hot_encoder.transform(X_single).toarray()
X_single = X_single[:,1:]

In [35]:
X_single

array([[0.e+00, 0.e+00, 6.e+02, 1.e+00, 4.e+01, 3.e+00, 6.e+04, 2.e+00,
        1.e+00, 1.e+00, 5.e+04]])

In [38]:
#Scaling
X_single = scaler.transform(X_single)

In [39]:
X_single

array([[-0.57946723, -0.57638802, -0.53598516,  0.91324755,  0.10479359,
        -0.69539349, -0.25781119,  0.80843615,  0.64920267,  0.97481699,
        -0.87683221]])

In [40]:
y_single = classifier.predict(X_single)

In [43]:
y_single = y_single > 0.5

In [44]:
y_single

array([[False]])

In [ ]:
#No

# K fold cross validation

In [24]:
from tensorflow.python.keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import cross_val_score

In [25]:
def build_classifier():
    classifier = Sequential()
    classifier.add(Dense(input_dim= 11, units= 6, kernel_initializer='uniform', activation='relu'))
    classifier.add(Dense(units= 6, kernel_initializer='uniform', activation='relu'))
    classifier.add(Dense(units= 1, kernel_initializer='uniform', activation='sigmoid'))
    classifier.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
    return classifier

In [26]:
classifier = KerasClassifier(build_fn=build_classifier, batch_size=10, epochs=100)

In [ ]:
accuracies = cross_val_score(classifier, X_train,y_train, cv= 10)

Epoch 1/100
7200/7200 [==============================]7200/7200 [==============================] - 2s 256us/step - loss: 1.2679 - acc: 0.6408

Epoch 2/100
7200/7200 [==============================]7200/7200 [==============================] - 2s 209us/step - loss: 0.5001 - acc: 0.7972

Epoch 3/100
7200/7200 [==============================]7200/7200 [==============================] - 2s 211us/step - loss: 0.4749 - acc: 0.8007

Epoch 4/100
7200/7200 [==============================]7200/7200 [==============================] - 2s 211us/step - loss: 0.4653 - acc: 0.8026

Epoch 5/100
7200/7200 [==============================]7200/7200 [==============================] - 2s 227us/step - loss: 0.4589 - acc: 0.8044

Epoch 6/100
7200/7200 [==============================]7200/7200 [==============================] - 2s 229us/step - loss: 0.4547 - acc: 0.8051

Epoch 7/100
7200/7200 [==============================]7200/7200 [==============================] - 2s 211us/step - loss: 0.4491 - acc: 0.8049


7200/7200 [==============================]7200/7200 [==============================] - 1s 199us/step - loss: 0.3354 - acc: 0.8607

Epoch 56/100
7200/7200 [==============================]7200/7200 [==============================] - 1s 202us/step - loss: 0.3353 - acc: 0.8617

Epoch 57/100
7200/7200 [==============================]7200/7200 [==============================] - 1s 202us/step - loss: 0.3348 - acc: 0.8617

Epoch 58/100
7200/7200 [==============================]7200/7200 [==============================] - 1s 204us/step - loss: 0.3349 - acc: 0.861000 [=========>....................] - ETA: 0s - loss: 0

Epoch 59/100
7200/7200 [==============================]7200/7200 [==============================] - 2s 240us/step - loss: 0.3346 - acc: 0.8606 0s - loss: 0.3317 - acc: 

Epoch 60/100
7200/7200 [==============================]7200/7200 [==============================] - 2s 256us/step - loss: 0.3350 - acc: 0.8608 1s - loss: 0.3302 - acc: 0.86 - ETA: 0s - loss

Epoch 61/100
7200/720

7200/7200 [==============================]7200/7200 [==============================] - 1s 205us/step - loss: 0.3974 - acc: 0.8286

Epoch 9/100
7200/7200 [==============================]7200/7200 [==============================] - 1s 202us/step - loss: 0.3884 - acc: 0.8344

Epoch 10/100
7200/7200 [==============================]7200/7200 [==============================] - 1s 204us/step - loss: 0.3826 - acc: 0.8369

Epoch 11/100
7200/7200 [==============================]7200/7200 [==============================] - 2s 240us/step - loss: 0.3786 - acc: 0.8389 0s - loss: 0.3795 - acc: 0

Epoch 12/100
7200/7200 [==============================]7200/7200 [==============================] - 2s 254us/step - loss: 0.3750 - acc: 0.8408

Epoch 13/100
7200/7200 [==============================]7200/7200 [==============================] - 2s 224us/step - loss: 0.3715 - acc: 0.841700 [============================>.] - ETA: 0s - loss: 0.3716 - acc: 0.841

Epoch 14/100
7200/7200 [==========================

7200/7200 [==============================]7200/7200 [==============================] - 1s 204us/step - loss: 0.3379 - acc: 0.862800 [========>.....................] - ETA: 0s - loss: 

Epoch 64/100
7200/7200 [==============================]7200/7200 [==============================] - 2s 208us/step - loss: 0.3382 - acc: 0.8633

Epoch 65/100
7200/7200 [==============================]7200/7200 [==============================] - 1s 203us/step - loss: 0.3371 - acc: 0.8606

Epoch 66/100
7200/7200 [==============================]7200/7200 [==============================] - 2s 210us/step - loss: 0.3380 - acc: 0.8611

Epoch 67/100
7200/7200 [==============================]7200/7200 [==============================] - 2s 235us/step - loss: 0.3372 - acc: 0.8622

Epoch 68/100
7200/7200 [==============================]7200/7200 [==============================] - 2s 220us/step - loss: 0.3372 - acc: 0.8628

Epoch 69/100
7200/7200 [==============================]7200/7200 [=============================

7200/7200 [==============================]7200/7200 [==============================] - 2s 243us/step - loss: 0.3600 - acc: 0.8496

Epoch 16/100
7200/7200 [==============================]7200/7200 [==============================] - 2s 238us/step - loss: 0.3566 - acc: 0.8511 0s - loss: 0.3549 - acc: 0.

Epoch 17/100
7200/7200 [==============================]7200/7200 [==============================] - 2s 268us/step - loss: 0.3539 - acc: 0.8536

Epoch 18/100
7200/7200 [==============================]7200/7200 [==============================] - 2s 229us/step - loss: 0.3519 - acc: 0.8539

Epoch 19/100
7200/7200 [==============================]7200/7200 [==============================] - 2s 217us/step - loss: 0.3492 - acc: 0.8558

Epoch 20/100
7200/7200 [==============================]7200/7200 [==============================] - 2s 222us/step - loss: 0.3471 - acc: 0.8578

Epoch 21/100
7200/7200 [==============================]7200/7200 [==============================] - 2s 215us/step - loss:

7200/7200 [==============================]7200/7200 [==============================] - 1s 184us/step - loss: 0.3313 - acc: 0.8644

Epoch 71/100
7200/7200 [==============================]7200/7200 [==============================] - 1s 184us/step - loss: 0.3309 - acc: 0.8643

Epoch 72/100
7200/7200 [==============================]7200/7200 [==============================] - 1s 201us/step - loss: 0.3310 - acc: 0.8644

Epoch 73/100
7200/7200 [==============================]7200/7200 [==============================] - 1s 198us/step - loss: 0.3308 - acc: 0.8636

Epoch 74/100
7200/7200 [==============================]7200/7200 [==============================] - 1s 190us/step - loss: 0.3310 - acc: 0.8629

Epoch 75/100
7200/7200 [==============================]7200/7200 [==============================] - 1s 192us/step - loss: 0.3310 - acc: 0.8637

Epoch 76/100
7200/7200 [==============================]7200/7200 [==============================] - 1s 191us/step - loss: 0.3304 - acc: 0.8654

Epoch

7200/7200 [==============================]7200/7200 [==============================] - 2s 231us/step - loss: 0.3476 - acc: 0.8590

Epoch 25/100
7200/7200 [==============================]7200/7200 [==============================] - 2s 274us/step - loss: 0.3465 - acc: 0.8590

Epoch 26/100
7200/7200 [==============================]7200/7200 [==============================] - 2s 255us/step - loss: 0.3461 - acc: 0.8590

Epoch 27/100
7200/7200 [==============================]7200/7200 [==============================] - 2s 263us/step - loss: 0.3462 - acc: 0.8597

Epoch 28/100
7200/7200 [==============================]7200/7200 [==============================] - 2s 238us/step - loss: 0.3460 - acc: 0.860300 [>.............................] - ETA:

Epoch 29/100
7200/7200 [==============================]7200/7200 [==============================] - 2s 267us/step - loss: 0.3454 - acc: 0.8612

Epoch 30/100
7200/7200 [==============================]7200/7200 [==============================] - 2s 240u

7200/7200 [==============================]7200/7200 [==============================] - 2s 248us/step - loss: 0.3341 - acc: 0.8640

Epoch 78/100
7200/7200 [==============================]7200/7200 [==============================] - 2s 261us/step - loss: 0.3353 - acc: 0.8637

Epoch 79/100
7200/7200 [==============================]7200/7200 [==============================] - 2s 248us/step - loss: 0.3346 - acc: 0.8639

Epoch 80/100
7200/7200 [==============================]7200/7200 [==============================] - 2s 260us/step - loss: 0.3341 - acc: 0.8639

Epoch 81/100
7200/7200 [==============================]7200/7200 [==============================] - 2s 233us/step - loss: 0.3348 - acc: 0.8635

Epoch 82/100
7200/7200 [==============================]7200/7200 [==============================] - 2s 230us/step - loss: 0.3344 - acc: 0.8624

Epoch 83/100
7200/7200 [==============================]7200/7200 [==============================] - 2s 277us/step - loss: 0.3344 - acc: 0.8646

Epoch

7200/7200 [==============================]7200/7200 [==============================] - 2s 236us/step - loss: 0.3597 - acc: 0.848600 [=======================>......] - ETA: 0s - loss: 0.3590 - acc:

Epoch 31/100
7200/7200 [==============================]7200/7200 [==============================] - 2s 231us/step - loss: 0.3588 - acc: 0.8510

Epoch 32/100
7200/7200 [==============================]7200/7200 [==============================] - 2s 262us/step - loss: 0.3584 - acc: 0.8487

Epoch 33/100
7200/7200 [==============================]7200/7200 [==============================] - 2s 253us/step - loss: 0.3586 - acc: 0.8486

Epoch 34/100
7200/7200 [==============================]7200/7200 [==============================] - 2s 240us/step - loss: 0.3577 - acc: 0.8485

Epoch 35/100
7200/7200 [==============================]7200/7200 [==============================] - 2s 235us/step - loss: 0.3572 - acc: 0.8511

Epoch 36/100
7200/7200 [==============================]7200/7200 [================

7200/7200 [==============================]7200/7200 [==============================] - 2s 252us/step - loss: 0.3430 - acc: 0.8612

Epoch 81/100
7200/7200 [==============================]7200/7200 [==============================] - 2s 237us/step - loss: 0.3431 - acc: 0.860100 [=======>......................] - ETA: 1s - loss: 0.335440/7200 [=====================>........] - ETA: 0s - loss: 0.3449 - ac

Epoch 82/100
7200/7200 [==============================]7200/7200 [==============================] - 2s 243us/step - loss: 0.3436 - acc: 0.859000 [=====>........................] - ETA: 1s -

Epoch 83/100
7200/7200 [==============================]7200/7200 [==============================] - 2s 240us/step - loss: 0.3425 - acc: 0.8603

Epoch 84/100
7200/7200 [==============================]7200/7200 [==============================] - 2s 245us/step - loss: 0.3436 - acc: 0.8603 0s - loss: 0.3417 - acc: 

Epoch 85/100
7200/7200 [==============================]7200/7200 [========================

7200/7200 [==============================]7200/7200 [==============================] - 2s 252us/step - loss: 0.3520 - acc: 0.8554 1s - los

Epoch 28/100
7200/7200 [==============================]7200/7200 [==============================] - 2s 231us/step - loss: 0.3511 - acc: 0.855300 [======>.......................] - ETA: 1s - loss:6550/7200 [==========================>...] - ETA: 0s - loss: 0.3500 - acc: 0.

Epoch 29/100
7200/7200 [==============================]7200/7200 [==============================] - 2s 275us/step - loss: 0.3505 - acc: 0.8561

Epoch 30/100
7200/7200 [==============================]7200/7200 [==============================] - 2s 275us/step - loss: 0.3494 - acc: 0.8572

Epoch 31/100
7200/7200 [==============================]7200/7200 [==============================] - 2s 253us/step - loss: 0.3487 - acc: 0.857900 [===========================>..] - ETA: 0s - loss: 0.3485 - acc: 0.8

Epoch 32/100
7200/7200 [==============================]7200/7200 [=================

7200/7200 [==============================]7200/7200 [==============================] - 3s 349us/step - loss: 0.3368 - acc: 0.8599 1s - loss: 0.3356 5610/7200 [======================>.......] - ETA: 0s - loss: 0.3329 - a

Epoch 80/100
7200/7200 [==============================]7200/7200 [==============================] - 2s 237us/step - loss: 0.3365 - acc: 0.8611

Epoch 81/100
7200/7200 [==============================]7200/7200 [==============================] - 2s 243us/step - loss: 0.3363 - acc: 0.8615

Epoch 82/100
7200/7200 [==============================]7200/7200 [==============================] - 2s 236us/step - loss: 0.3362 - acc: 0.859200 [===========>..................] - ETA: 1s - loss: 

Epoch 83/100
7200/7200 [==============================]7200/7200 [==============================] - 2s 239us/step - loss: 0.3357 - acc: 0.8632

Epoch 84/100
7200/7200 [==============================]7200/7200 [==============================] - 2s 242us/step - loss: 0.3361 - acc: 0.8597

Epoch


Epoch 31/100
7200/7200 [==============================]7200/7200 [==============================] - 2s 258us/step - loss: 0.3498 - acc: 0.8560

Epoch 32/100
7200/7200 [==============================]7200/7200 [==============================] - 2s 236us/step - loss: 0.3500 - acc: 0.8574

Epoch 33/100
7200/7200 [==============================]7200/7200 [==============================] - 2s 261us/step - loss: 0.3485 - acc: 0.8565

Epoch 34/100
7200/7200 [==============================]7200/7200 [==============================] - 2s 255us/step - loss: 0.3487 - acc: 0.856400 [===================>..........] - ETA: 0s - loss: 0.3519 - 

Epoch 35/100
7200/7200 [==============================]7200/7200 [==============================] - 2s 268us/step - loss: 0.3476 - acc: 0.8553

Epoch 36/100
7200/7200 [==============================]7200/7200 [==============================] - 2s 315us/step - loss: 0.3478 - acc: 0.8579

Epoch 37/100
7200/7200 [==============================]7200/7200 [======

7200/7200 [==============================]7200/7200 [==============================] - 2s 234us/step - loss: 0.3396 - acc: 0.8607

Epoch 86/100
7200/7200 [==============================]7200/7200 [==============================] - 2s 224us/step - loss: 0.3399 - acc: 0.8611

Epoch 87/100
7200/7200 [==============================]7200/7200 [==============================] - 2s 242us/step - loss: 0.3397 - acc: 0.8625

Epoch 88/100
7200/7200 [==============================]7200/7200 [==============================] - 2s 221us/step - loss: 0.3395 - acc: 0.8621

Epoch 89/100
7200/7200 [==============================]7200/7200 [==============================] - 2s 234us/step - loss: 0.3393 - acc: 0.8621

Epoch 90/100
7200/7200 [==============================]7200/7200 [==============================] - 2s 267us/step - loss: 0.3387 - acc: 0.8604

Epoch 91/100
7200/7200 [==============================]7200/7200 [==============================] - 2s 239us/step - loss: 0.3386 - acc: 0.8610

Epoch

7200/7200 [==============================]7200/7200 [==============================] - 2s 257us/step - loss: 0.3320 - acc: 0.863300 [==================>...........] - ETA: 0s - loss: 0.3367 

Epoch 39/100
7200/7200 [==============================]7200/7200 [==============================] - 2s 246us/step - loss: 0.3313 - acc: 0.8656

Epoch 40/100
7200/7200 [==============================]7200/7200 [==============================] - 2s 246us/step - loss: 0.3317 - acc: 0.8632

Epoch 41/100
7200/7200 [==============================]7200/7200 [==============================] - 2s 243us/step - loss: 0.3311 - acc: 0.863500 [==============>...............] - ETA: 0s - loss: 0.

Epoch 42/100
7200/7200 [==============================]7200/7200 [==============================] - 2s 263us/step - loss: 0.3312 - acc: 0.8628

Epoch 43/100
7200/7200 [==============================]7200/7200 [==============================] - 2s 246us/step - loss: 0.3316 - acc: 0.8642

Epoch 44/100
7200/7200 [========

7200/7200 [==============================]7200/7200 [==============================] - 2s 239us/step - loss: 0.3279 - acc: 0.8633

Epoch 92/100
7200/7200 [==============================]7200/7200 [==============================] - 2s 244us/step - loss: 0.3279 - acc: 0.8660

Epoch 93/100
7200/7200 [==============================]7200/7200 [==============================] - 2s 244us/step - loss: 0.3278 - acc: 0.864700 [========================>.....] - ETA: 0s - loss: 0.3317 - acc: 

Epoch 94/100
7200/7200 [==============================]7200/7200 [==============================] - 2s 242us/step - loss: 0.3277 - acc: 0.8676 0s - loss: 0.3

Epoch 95/100
7200/7200 [==============================]7200/7200 [==============================] - 2s 238us/step - loss: 0.3275 - acc: 0.8647

Epoch 96/100
7200/7200 [==============================]7200/7200 [==============================] - 2s 265us/step - loss: 0.3276 - acc: 0.8656

Epoch 97/100
7200/7200 [==============================]7200/7200 [