In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
dataset = pd.read_csv('Churn_Modelling.csv')

In [3]:
dataset.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [4]:
X = dataset.iloc[:,3:-1].values
y = dataset.iloc[:,-1].values

In [5]:
print(X[0])

[619 'France' 'Female' 42 2 0.0 1 1 1 101348.88]


In [6]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

In [7]:
label_encoder_X1 = LabelEncoder()
X[:,1] = label_encoder_X1.fit_transform(X[:,1])

In [8]:
label_encoder_X2 = LabelEncoder()
X[:,2] = label_encoder_X2.fit_transform(X[:,2])

In [9]:
one_hot_encoder = OneHotEncoder(categorical_features=[1])

In [10]:
X = one_hot_encoder.fit_transform(X).toarray()

In [11]:
#To avoid dummy variable trap
X = X[:,1:]

In [12]:
from sklearn.model_selection import train_test_split

In [13]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [14]:
from sklearn.preprocessing import StandardScaler

In [15]:
scaler = StandardScaler()

In [16]:
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [17]:
print('Shape of training set {}'.format(X_train.shape))

Shape of training set (8000, 11)


In [18]:
from tensorflow.python.keras.models import Sequential
from tensorflow.python.keras.layers import Dense

/Users/tari/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [19]:
classifier = Sequential()

In [20]:
#1st hidden layer
classifier.add(Dense(input_dim= 11, units= 6, kernel_initializer='uniform', activation='relu'))

In [21]:
#2nd hidden layer
classifier.add(Dense(units= 6, kernel_initializer='uniform', activation='relu'))

In [22]:
#Output layer
classifier.add(Dense(units= 1, kernel_initializer='uniform', activation='sigmoid'))

In [23]:
#Compile the model with certain hyperparameters
classifier.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [24]:
classifier.fit(X_train, y_train, batch_size=10, epochs=100, n_jobs=-1)

Epoch 1/100
8000/8000 [==============================]8000/8000 [==============================] - 2s 274us/step - loss: 1.2704 - acc: 0.6518

Epoch 2/100
8000/8000 [==============================]8000/8000 [==============================] - 2s 204us/step - loss: 0.5028 - acc: 0.7957

Epoch 3/100
8000/8000 [==============================]8000/8000 [==============================] - 2s 206us/step - loss: 0.4685 - acc: 0.8014

Epoch 4/100
8000/8000 [==============================]8000/8000 [==============================] - 2s 231us/step - loss: 0.4576 - acc: 0.8040 0s - loss: 0.4523

Epoch 5/100
8000/8000 [==============================]8000/8000 [==============================] - 2s 242us/step - loss: 0.4537 - acc: 0.8042

Epoch 6/100
8000/8000 [==============================]8000/8000 [==============================] - 2s 212us/step - loss: 0.4497 - acc: 0.8055

Epoch 7/100
8000/8000 [==============================]8000/8000 [==============================] - 2s 213us/step - loss: 0.4

8000/8000 [==============================]8000/8000 [==============================] - 2s 201us/step - loss: 0.3335 - acc: 0.8644

Epoch 55/100
8000/8000 [==============================]8000/8000 [==============================] - 2s 203us/step - loss: 0.3337 - acc: 0.8654

Epoch 56/100
8000/8000 [==============================]8000/8000 [==============================] - 2s 203us/step - loss: 0.3334 - acc: 0.8650

Epoch 57/100
8000/8000 [==============================]8000/8000 [==============================] - 2s 203us/step - loss: 0.3332 - acc: 0.8650

Epoch 58/100
8000/8000 [==============================]8000/8000 [==============================] - 2s 205us/step - loss: 0.3331 - acc: 0.8660

Epoch 59/100
8000/8000 [==============================]8000/8000 [==============================] - 2s 223us/step - loss: 0.3329 - acc: 0.8644 0s - loss: 0.3325 - acc: 0

Epoch 60/100
8000/8000 [==============================]8000/8000 [==============================] - 2s 233us/step - loss: 

In [25]:
#Testing the model performance on a testing set
y_pred = classifier.predict(X_test)

In [26]:
y_pred = y_pred > 0.5

In [27]:
from sklearn.metrics import confusion_matrix, f1_score, accuracy_score

In [28]:
confusion_matrix(y_test, y_pred)

array([[1550,   57],
       [ 214,  179]])

In [29]:
print('f1 score ', f1_score(y_test, y_pred))

f1 score  0.5691573926868045


In [30]:
print('Accuracy score ', accuracy_score(y_test, y_pred))

Accuracy score  0.8645


# Single prediction
 - Geography: France
 - Credit Score: 600
 - Gender: Male
 - Age: 40 years old
 - Tenure: 3 years
 - Balance: 60000 USD
 - Number of Products: 2
 - Does this customer have a credit card ? Yes
 - Is this customer an Active Member: Yes
 - Estimated Salary: $50000

In [31]:
single_pred = pd.Series([600, 'France', 'Male', 40, 3, 60000, 2, 1, 1, 50000])

In [32]:
X_single = single_pred.values
X_single = np.reshape(X_single, (1,10))
X_single

array([[600, 'France', 'Male', 40, 3, 60000, 2, 1, 1, 50000]],
      dtype=object)

In [33]:
X_single[:,1] = label_encoder_X1.transform(X_single[:,1])
X_single[:,2] = label_encoder_X2.transform(X_single[:,2])

In [34]:
X_single = one_hot_encoder.transform(X_single).toarray()
X_single = X_single[:,1:]

In [35]:
X_single

array([[0.e+00, 0.e+00, 6.e+02, 1.e+00, 4.e+01, 3.e+00, 6.e+04, 2.e+00,
        1.e+00, 1.e+00, 5.e+04]])

In [38]:
#Scaling
X_single = scaler.transform(X_single)

In [39]:
X_single

array([[-0.57946723, -0.57638802, -0.53598516,  0.91324755,  0.10479359,
        -0.69539349, -0.25781119,  0.80843615,  0.64920267,  0.97481699,
        -0.87683221]])

In [40]:
y_single = classifier.predict(X_single)

In [43]:
y_single = y_single > 0.5

In [44]:
y_single

array([[False]])

In [ ]:
#No